### ISSUE TITLE
Extension won't fetch data for a long time (if at all)

### ISSUE THREAD

**Issue by leo-liar** [kkkrist/chromium-notifier#26]
Hello again,

another (possible) bug: I sometimes have the problem that the extension is taking ages (haven't measured yet exactly how long, but it is running unchanged now for over an hour) for it to actually finish its search for updates ("Waiting for data...").
I don't yet know which combination of browser restart(s), extension reloads and just waiting reliably resolves this.

See the screenshots below for the error messages.

<details><summary><b>Console-Tab</b></summary>

---

During these times the console shows an error like this:
![image](https://user-images.githubusercontent.com/25538015/69219087-5cd71c00-0b72-11ea-962c-d55a06327621.png)

Which leads to the following part in `background.js`:
![image](https://user-images.githubusercontent.com/25538015/69223025-e2f76080-0b7a-11ea-9a6c-e62c89052b42.png)

---

All the while the console for the pop-up shows this:
![image](https://user-images.githubusercontent.com/25538015/69223373-8779a280-0b7b-11ea-9fae-b61484e42820.png)

With this corresponding part in `popup.js`:
![image](https://user-images.githubusercontent.com/25538015/69223675-e3dcc200-0b7b-11ea-8a23-80de75c4b21e.png)

</details>

EDIT:
With v1.7.3 this still occurs but the error in `background.js` is gone! Errors in `popup.js` are still there. (With the same error messages.)

**Comment by kkkrist** [comment]
Thanks again for your help!

This might be an error in the [proxy](https://github.com/kkkrist/chromium-extension-service), it responds with a 500 ("Internal Server Error") to the request.

Can you see any details of the 500 response in the network tab of the popup devtools? I'd be interested in the Request and Response body, see screenshot below.

<details>
<summary>Screenshot</summary>
<img width="1220" alt="Bildschirmfoto 2019-11-20 um 13 54 01" src="https://user-images.githubusercontent.com/3873068/69242014-48aa1380-0ba0-11ea-9f94-2e55a1387301.png">
<img width="1220" alt="Bildschirmfoto 2019-11-20 um 14 02 51" src="https://user-images.githubusercontent.com/3873068/69242012-48aa1380-0ba0-11ea-999e-606109453c23.png">
</details>

You can switch "Track extension updates" off and on again(™️) to trigger reloading. If you keep the popup devtools open while doing so, it will record the network activity.

I found this in the server logs, maybe it's related:

```
2019-11-20T07:35:40.554Z	24f1c408-6771-476b-99d3-9822d7c41129	ERROR	{
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('mismatched tag')
     at Parser.emit (events.js:187:17)
     at Parser.write (/var/task/node_modules/node-expat/lib/node-expat.js:68:10)
     at Parser.parse (/var/task/node_modules/xmltwojs/index.js:21:26)
     at Object.parse (/var/task/node_modules/xmltwojs/index.js:62:17)
     at getFreshEntries (/var/task/api/index.js:35:29)
     at process._tickCallback (internal/process/next_tick.js:68:7) context: 'mismatched tag' }
Duration: 639.94 ms  Billed Duration: 700 ms  Memory Size: 3008 MB  Max Memory Used: 105 MB
```
It means an `update_url` endpoint of some extension has responded with something the xml parser can't handle. I'll add extra logging to the proxy to hopefully get more insight.

P.S.: Extra props for wrapping the screenshots in a `<details>` tag ;-)

**Comment by leo-liar** [comment]
I just checked the extension again and just about 15mins ago it finally updated (_Last update: 20.11.2019, 14:14:07_).

Therefore I don't see any error messages right now but I will keep track and update my post here in case this happens again.

---

> You can switch "Track extension updates" off and on again(™️) to trigger reloading. If you keep the popup devtools open while doing so, it will record the network activity.

During the error period the pop-up wasn't fully loading. It just looked like this with all the options either inaccessible or greyed out:
![image](https://user-images.githubusercontent.com/25538015/69242892-21ecdc80-0ba2-11ea-9cbc-7390f37aa6c9.png)
(This is a mock-up made from memory but some options were just missing.)

---

EDIT:
I just took a look in the network tab of the devtools but right now it looks pretty similar to the screenshots you posted.

<details><summary><b>Network</b></summary>

![image](https://user-images.githubusercontent.com/25538015/69244001-74c79380-0ba4-11ea-9138-b34017a4d2e0.png)

![image](https://user-images.githubusercontent.com/25538015/69244010-7abd7480-0ba4-11ea-9da4-6f24695ff6d7.png)

</details>

**Comment by kkkrist** [comment]
I guess one of the `update_url` endpoints of your installed extensions sometimes either sends an unexpected response or time out.

I would like to add some guards against this in the proxy, but I need to know how the unexpected response looks like first. If you don't mind to send me the `update_url`s and `id`s of your extensions, I could try to reproduce it.  Just run this in the popup or background devtools console and send me the output via mail (github -at- cmund -dot- de):

```
chrome.management.getAll(exts => console.log(JSON.stringify(exts.map(({ id, updateUrl }) => ({ id, updateUrl })))))
```

If not (which is totally fine), I'll just wait for the (now more verbose) logs on the server.

**Comment by leo-liar** [comment]
Just fyi in case it landed in the spam folder: I sent you an e-mail with the requested data.

EDIT:
Just restarted and got the never ending fetching again. Like I remembered, the pop-up menu is malformed and barely no activity is visible at all in devtools network panel. Please see below.

<details><summary><b>screenshots</b></summary>

---

Malformed pop-up menu:
![image](https://user-images.githubusercontent.com/25538015/69274339-74e28600-0bda-11ea-9abc-5619b717c7fb.png)

![image](https://user-images.githubusercontent.com/25538015/69274355-79a73a00-0bda-11ea-87df-cf7d90fb048d.png)

---

Network tab in devtools:
![image](https://user-images.githubusercontent.com/25538015/69274520-cd198800-0bda-11ea-9861-0ac8e8e9c8e3.png)

---

Error messages:
![image](https://user-images.githubusercontent.com/25538015/69274677-271a4d80-0bdb-11ea-9a34-5bbfeedd4d59.png)

![image](https://user-images.githubusercontent.com/25538015/69274690-30a3b580-0bdb-11ea-99d3-d9ee80a01c4d.png)

The `pop-up.js` error messages are the same as before.

</details>

**Comment by kkkrist** [comment]
Got your mail, thanks! I'm a bit busy currently, will look into it tomorrow.

**Comment by leo-liar** [comment]
Ah, sorry! I didn't mean to rush you. It's a free extension and the bug is more of an annoyance and not an urgent matter after all.
Thanks again for your effort.

**Comment by kkkrist** [comment]
No worries :-)

The `update_url` endpoint of the extension you had under suspicion indeed responds with just an empty body most of the time (despite sending a 200 status code; looks like it's buggy). This is something the proxy didn't know how to deal with. I've just pushed an update to it which should make it handle these kind of responses gracefully.

I've also updated the extension so that it now lists extensions whose `update_url`s don't respond with a valid `version` under "No update info available". Both commits together should fix the issue.

Could you please pull master and see if it works now?

**Comment by leo-liar** [comment]
Mh, thanks for the update but unfortunately this does _not_ resolve the issue.
I pulled the commit and reloaded the extension, which didn't help and then restartet the browser but still to no avail. It's been fetching and waiting for data ever since.

See the error messages below (pretty much the same, the line count changed a bit due to your updated code). The pop-up is still malformed while waiting.

<details><summary><b>Errors</b></summary>

---

![image](https://user-images.githubusercontent.com/25538015/69338702-0e09af00-0c64-11ea-9185-cf28a5407226.png)

![image](https://user-images.githubusercontent.com/25538015/69338721-15c95380-0c64-11ea-9d5b-aa043e97d9c8.png)

</details>

I even tried removing the "sci-hub" extension, then reloaded but that did not help either.

**Comment by kkkrist** [comment]
Do you actually use the proxy ("increase privacy" option under settings)? I've found out that direct requests to the `update_url` of said extension will fail with CORS errors. The endpoint of said extension doesn't set permissive `Access-Control-Allow-Origin` headers. That should definitely be handled more gracefully by the extension too.

I reproduced your requests and sent them to the proxy (i.e. "increase privacy" enabled) and the proxy responded as expected every time.

TBC

**Comment by leo-liar** [comment]
> Do you actually use the proxy ("increase privacy" option under settings)?

Yes, this option is set. Though I don't know if it's working right now because it's still "Waiting for data..." and due to the pop-up not fully loading I can't check on (or if necessary) re-activate this option.

**Comment by kkkrist** [comment]
Thanks for being patient :) I will do a full test case w/ your set of installed extensions when I have more time and see if that leads to more insight.

**Comment by leo-liar** [comment]
Thanks for still trying to figure this out! I am really curious what's causing this behaviour but like I said before it's not the end of the world and more of an inconvenience than anything else.

EDIT:
No pressure or anything BUT I left my laptop running overnight and since I pulled your fixes yesterday the extension is waiting for data ... seems like that last fix actually made it worse 😄

**Comment by kkkrist** [comment]
The reason the popup gets stuck in the "waiting for data…" state is that the Preact app that renders it did not contain any error boundaries. So as soon an error was thrown somewhere in its render tree (presumably when `getExtensionsInfo` was called as a side-effect of enabling "increase privacy"), it would just stop working, i.e. not show errors or react to store changes any more.

I've just pushed a few commits that revamp much of the overall error handling:
- popup: 
  - wrapped all sections into an error boundary
  - catch all errors with the error tracker (was only used in the background page before)
- utils
  - fixed handling of event type "unhandledrejection" in error tracker
  - use `Promise.prototype.allSettled` instead of `Promise.prototype.all` to handle fetch errors gracefully in `fetchExtensionsInfo` (e.g. above mentioned CORS errors; requires Chromium v76+)
- proxy
  - omit extensions with incomplete update info from response (i.e. empty responses, missing `updatecheck.version` etc.)

Please pull master and try again. If you still see errors or the extension somehow acts up, please also try re-installing to clear the store. Thank you!

**Comment by leo-liar** [comment]
Wow, I first had to roll back to `master` (tried to get the extension working again after my last comment with `git checkout` to the previous commit) but after pulling it now immediately loads up, shows my extensions, keeps its settings and the console logs for `background.html` and `popup.html` are completely error free. Awesome!
It seems to work perfectly now. Will keep an eye on it and report back later (probably after the weekend). If everything keeps being fine I will close this issue.

Thanks for all your effort and for fixing the bugs!

**Comment by kkkrist** [comment]
Thanks for the feedback! I'm glad it finally works!

Judging by the error logs, there are about a dozen other users who frequently experience similar errors. There is probably more than one extension with a broken `update_url` endpoint out there…

I think, I'll better publish fd84c6789a547e9c8845cf0c48c9d625c71a413f as v1.8.0 now. But please keep testing anyway and report back!

**Comment by leo-liar** [comment]
Hello there,

I unfortunately am the bearer of bad news. I just fired up the laptop and pulled the latest commit fd84c67 and got some new errors right after starting the browser. Please see the attached pictures. All errors are in `background.html`, `popup.html` is fine.

I don't yet know if these will vanish after some time (it's been running for about 30mins).

<details><summary><b>Errors</b></summary>

---

Extension pop-up:
![image](https://user-images.githubusercontent.com/25538015/69475643-cb64e580-0dcf-11ea-8494-d7b921b272d0.png)

Error messages in console:
![image](https://user-images.githubusercontent.com/25538015/69475678-46c69700-0dd0-11ea-8640-36866116d36f.png)

After some time the `status 500` error disappeared:
![image](https://user-images.githubusercontent.com/25538015/69475707-97d68b00-0dd0-11ea-88f9-b9ceb94d5dc0.png)

</details>

EDIT:
Forcing a few reloads by dis- and enabling extension tracking (and error tracking) lead to the reapperance of the extension setting part in the pop-up with still an error shown below.
![image](https://user-images.githubusercontent.com/25538015/69475834-69f24600-0dd2-11ea-9169-53a8c811f686.png)

**Comment by kkkrist** [comment]
No worries, wel'll get there :-)

I'm pretty sure the reason for all of this is one of your extension's `update_url` endpoint intermittently responding with malformed xml (or a string that the parser interprets as malformed xml).

Fortunately, Zeit have bumped Node from v10 to v12, so I can now use `Promise.prototype.allSettled` in the proxy as well.

Could you check out the "proxy-all-settled" branch and see if that helps?

**Comment by leo-liar** [comment]
Hey there,

after pulling all changes, switching to the `proxy-all-settled` branch and forcing a reload via dis- and re-enabling the "Track extension updates" setting all errors are gone. Force reloading the extension in chromium and restarting the browser didn't lead to new errors so far.

Looks good!

**Comment by kkkrist** [comment]
Sounds promising! I'll release this and a few other little tweaks as 1.8.1 in a minute.

**Comment by leo-liar** [comment]
I just switched back to the `master`branch und pulled the 1.8.1 update. So far no error at all and everthing works fine.
I hope I can soon test the how the extension works in case there is an update (the latest uBlock Origin update should hit the webstore anytime now) but right now I'm inclined to close this issue as solved.

**Comment by kkkrist** [comment]
Switching the proxy to `Promise.allSettled` seems to have done the trick. I haven't seen any errors in the proxy since then. The extension error tracker did catch (very few) "Failed to fetch" errors, but those must have been caused by version prior to 1.7.1 (missing a few attributes I added later).

**Comment by leo-liar** [comment]
Yep, seems that way. I haven't encountered any new errors so far. Only scenario which might show yet undiscovered errors IMHO will be extension updates because we/I weren't able to observe one of those occasions during this issue.

That beeing said, thanks again for your effort in solving this issue!

**Comment by kkkrist** [comment]
No problem :) Be free to re-open should the issue come back.

Fun fact: uBlock Origin is so popular that the proxy usually receives more requests for it than for this extension itself
